export const Constants = {
  // data types for websocket messages
  MACHINE_STATUS_DATA_TYPE: 'MACHINE_STATUS' as string,
  SERIAL_COMMAND_DATA_TYPE: 'SERIAL_COMMAND' as string,
  FILE_EXECUTION_DATA_TYPE: 'FILE_EXECUTION' as string,
  REAL_TIME_COMMAND_DATA_TYPE: 'REAL_TIME_COMMAND' as string,
  NORMAL_COMMAND_DATA_TYPE: 'NORMAL_COMMAND' as string,
  MACHINE_CONNECTION_DATA_TYPE: 'MACHINE_CONNECTION' as string,
  FILE_MANAGER_DATA_TYPE: 'FILE_MANAGER' as string,
  CONNECTION_DATA_TYPE: 'CONNECTION' as string,
  CAMERAS_SYSTEM_DATA_TYPE: 'CAMERAS_SYSTEM' as string,

  // small notes/messages
  SMALL_MESSAGES: {
    DISCONNECTED_MESSAGE: 'Server/Machine is disconnected',
    ALARM_MESSAGE: 'Alarm detected on the machine',
    HOLD_MESSAGE: 'Machine on hold/pause',
    RUN_MESSAGE: 'Machine is running',
    IDLE_MESSAGE: 'Machine is ready to start',
    ERROR_MESSAGE: 'Error detected during running the machine ',
  } as Record<string, string>,

  // long messages
  LONG_MESSAGES: {
    DISCONNECTED_MESSAGE:
      'The machine is currently disconnected. Check the server connection and ensure the machine is properly connected.',
    HOLD_MESSAGE:
      'The machine is on hold. Please review the status and take necessary actions to resume operation.',
    RUN_MESSAGE:
      'The machine is currently in operation. All systems are functioning normally.',
    IDLE_MESSAGE:
      'The machine is idle and waiting for the next job. All systems are ready for operation.',
    ALARM_MESSAGES: [
      'Unknown alarm code. Check the machine and G-code for issues.',
      'Hard limit triggered. Position is likely lost due to a sudden and immediate halt. Re-homing is highly recommended before resuming.',
      'Soft limit alarm. Position is kept, and unlocking is safe. Review soft limit settings and program size.',
      'Reset while in motion. Position is lost. Investigate and resolve the cause before continuing.',
      'Probe fail. Probe is not in the expected initial state. Check probe wiring and connections.',
      'Probe fail. Probe did not contact the work. Check probe, wiring, and workpiece setup.',
      'Homing fail. The active homing cycle was reset. Investigate and resolve homing issues.',
      'Homing fail. Door opened during homing cycle. Ensure the door remains closed during homing.',
      'Homing fail. Pull off failed to clear limit switch. Check limit switch wiring and position.',
      'Homing fail. Could not find limit switch. Check limit switch wiring and position.',
    ],
    ERROR_MESSAGES: [
      'Unknown error code. Check the machine and G-code for issues.',
      'GCode Command letter was not found. Check the GCode command for typos or missing letters.',
      'GCode Command value invalid or missing. Ensure that the GCode command includes a valid value.',
      "Grbl '$' not recognized or supported. Check the GCode program for unsupported commands.",
      'Negative value for an expected positive value. Ensure that all values in the GCode command are positive.',
      'Homing fail. Homing is not enabled in settings. Enable homing in Grbl settings.',
      'Min step pulse must be greater than 3usec. Adjust the step pulse duration in Grbl settings.',
      'EEPROM read failed. Default values used. Check the EEPROM and ensure it is functioning correctly.',
      "Grbl '$' command Only valid when Idle. Ensure that the Grbl machine is in an idle state before using '$' commands.",
      'GCode commands invalid in alarm or jog state. Check the machine state and send GCode commands when the machine is not in an alarm or jog state.',
      'Soft limits require homing to be enabled. Enable homing in Grbl settings to use soft limits.',
      'Max characters per line exceeded. Ignored. Check the GCode program for lines that exceed the maximum allowed length.',
      "Grbl '$' setting exceeds the maximum step rate. Adjust the step rate settings in Grbl.",
      'Safety door opened and door state initiated. Close the safety door to resume operation.',
      'Build info or start-up line > EEPROM line length. Check the EEPROM and ensure it can store the build information or start-up line.',
      'Jog target exceeds machine travel, ignored. Check the jog commands and ensure they are within the machine travel limits.',
      "Jog Cmd missing '=' or has prohibited GCode. Check the jog commands and correct any syntax errors.",
      'Laser mode requires PWM output. Ensure that the machine setup supports PWM output for laser mode.',
      '', // no code
      '', // no code
      'Unsupported or invalid GCode command. Check the GCode program for unsupported or invalid commands.',
      '> 1 GCode command in a modal group in block. Ensure that each GCode block contains only one command from a modal group.',
      'Feed rate has not yet been set or is undefined. Set the feed rate using the F command in the GCode program.',
      'GCode command requires an integer value. Check the GCode program and provide integer values where required.',
      '> 1 GCode command using axis words found. Each GCode block should contain only one GCode command using axis words.',
      'Repeated GCode word found in block. Check the GCode program for repeated words in the same block.',
      'No axis words found in command block. Provide axis words in the GCode command.',
      'Line number value is invalid. Check the GCode program for invalid line number values.',
      'GCode Cmd missing a required value word. Check the GCode program for missing required value words in commands.',
      'G59.x WCS are not supported. Check the GCode program and use a supported WCS.',
      'G53 only valid with G0 and G1 motion modes. Use G53 only with G0 and G1 motion modes in the GCode program.',
      'Unneeded Axis words found in block. Remove unnecessary axis words from the GCode command block.',
      'G2/G3 arcs need >= 1 in-plane axis word. Provide at least one in-plane axis word for G2/G3 arcs in the GCode program.',
      'Motion command target is invalid. Check the motion command and provide a valid target.',
      'Arc radius value is invalid. Check the GCode program for invalid arc radius values.',
      'G2/G3 arcs need >= 1 in-plane offset word. Provide at least one in-plane offset word for G2/G3 arcs in the GCode program.',
      'Unused value words found in block. Remove unused value words from the GCode command block.',
      'G43.1 offset not assigned to tool length axis. Ensure that the G43.1 offset is assigned to the tool length axis.',
      'Tool number greater than max value. Check the tool number in the GCode program and ensure it is within the supported range.',
    ],
  } as Record<string, string | string[]>,

  FILE_MANAGER_ERRORS: {
    CHECK_OPEN_FILE: 'Error Check Open File',
    OPEN_FILE: 'Error Open File',
    DELETE_FILE: 'Error Delete File',
    RENAME_FILE: 'Error Rename File',
    START_FILE: 'Error Start File',
    PREVIEW_FILE: 'Error Preview File',
  } as Record<string, string>,

  // Real time commands
  GRBL_COMMAND_STATUS: '?' as string,
  GRBL_COMMAND_PAUSE: '!' as string,
  GRBL_COMMAND_RESUME: '~' as string,
  GRBL_COMMAND_STOP: '\x18' as string,

  GRBL_COMMAND_INCREASE_FEED_RATE_1: '\x93' as string,
  GRBL_COMMAND_DECREASE_FEED_RATE_1: '\x94' as string,
  GRBL_COMMAND_INCREASE_FEED_RATE_10: '\x91' as string,
  GRBL_COMMAND_DECREASE_FEED_RATE_10: '\x92' as string,
  GRBL_COMMAND_DEFAULT_FEED_RATE: '\x90' as string,

  GRBL_COMMAND_INCREASE_LASER_POWER_1: '\x9C' as string,
  GRBL_COMMAND_DECREASE_LASER_POWER_1: '\x9D' as string,
  GRBL_COMMAND_INCREASE_LASER_POWER_10: '\x9A' as string,
  GRBL_COMMAND_DECREASE_LASER_POWER_10: '\x9B' as string,
  GRBL_COMMAND_DEFAULT_LASER_POWER: '\x99' as string,

  GRBL_COMMAND_INCREASE_SPINDLE_SPEED_1: '\x9C' as string,
  GRBL_COMMAND_DECREASE_SPINDLE_SPEED_1: '\x9D' as string,
  GRBL_COMMAND_INCREASE_SPINDLE_SPEED_10: '\x9A' as string,
  GRBL_COMMAND_DECREASE_SPINDLE_SPEED_10: '\x9B' as string,
  GRBL_COMMAND_DEFAULT_SPINDLE_SPEED: '\x99' as string,

  // essential commands
  GRBL_COMMAND_HOMING: '$H' as string,
  GRBL_COMMAND_RESET_ZERO: 'G92 X0 Y0 Z0' as string,
  GRBL_COMMAND_UNLOCK: '$X' as string,
  GRBL_COMMAND_SOFT_RESET: '\x18' as string,

  // Jogging commands
  COMMAND_RETURN_ZERO: 'G1 X0 Y0 F2000' as string,
  COMMAND_RESET_ZERO: 'G92 X0 Y0 Z0' as string,
  COMMAND_RESET_ZERO_X: 'G92 X0' as string,
  COMMAND_RESET_ZERO_Y: 'G92 Y0' as string,
  COMMAND_RESET_ZERO_Z: 'G92 Z0' as string,
  COMMAND_RESET_ZERO_XY: 'G92 X0 Y0' as string,
  COMMAND_RESET_ZERO_XYZ: 'G92 X0 Y0 Z0' as string,
  COMMAND_ABSOLUTE_POSITION: 'G90' as string,
  COMMAND_RELATIVE_POSITION: 'G91' as string,

  // machine states
  DISCONNECTED: 'Disconnected' as string,
  HOLD: 'Hold' as string,
  RUN: 'Run' as string,
  IDLE: 'Idle' as string,
  ALARM: 'Alarm' as string,
  ERROR: 'Error' as string,
  CONNECTED: 'Connected' as string,
  API_URI: {
    // USER: `${API_VERSION.V1}/user`,
    FILES: 'api/file_manager/',
    // LOGOUT: `${API_VERSION.V1}/auth/logout`,
  } as Record<string, string>,

  // drawing on canvas functionalities
  IMAGE_DRAW_TYPE: {
    CUT_MARK: 'cut/mark',
    ENGRAVE: 'engrave',
  } as Record<string, string>,

  MAX_FILE_SIZE: 524288000 as number, // 500 MB
  MAX_IMAGE_FILE_SIZE: 52428800 as number, //50MB
  GCODE_COMMAND: 'Gcode Command' as string,

  GRAPH_STEP_SIZE: 50 as number,
  PLATFORM_HEIGHT: 600 as number, // mm
  PLATFORM_WIDTH: 1000 as number, // mm

  SVG_ELEMENTS_FILTER: {
    SHAPE: 'shape',
    COLOR: 'color',
  } as Record<string, string>,

  DITHERING_ALGORITHMS: {
    FLOYDSTEINBERG: 'Floyd-Steinberg',
    ORDERED: 'ordered',
    HALFTONE: 'halftone',
    RANDOM: 'random',
    AVERAGE: 'average',
    GRID: 'grid',
  } as Record<string, string>,

  PROFILE_OPTIONS: {
    NOTHING: '-----',
    CUT: 'Cut',
    MARK: 'Mark',
    ENGRAVE: 'Engrave',
  } as Record<string, string>,

  PROFILE_ALL_OPTIONS: {
    NOTHING: '-----',
    CUT_EVERYTHING: 'Cut Everything',
    MARK_EVERYTHING: 'Mark Everything',
    ENGRAVE_EVERYTHING: 'Engrave Everything',
  } as Record<string, string>,

  SVG_ALLOWED_ELEMENTS: [
    'rect',
    'circle',
    'ellipse',
    'line',
    'polyine',
    'polygon',
    'path',
    'text',
  ] as string[],

  RGB_COLOR: {
    BLACK: 'rgb(0, 0, 0)',
    WHITE: 'rgb(255, 255, 255)',
  } as Record<string, string>,

  ALL_HEX_COLORS: {
    ALICEBLUE: '#f0f8ff',
    ANTIQUEWHITE: '#faebd7',
    AQUA: '#00ffff',
    AQUAMARINE: '#7fffd4',
    AZURE: '#f0ffff',
    BEIGE: '#f5f5dc',
    BISQUE: '#ffe4c4',
    BLACK: '#000000',
    BLANCHEDALMOND: '#ffebcd',
    BLUE: '#0000ff',
    BLUEVIOLET: '#8a2be2',
    BROWN: '#a52a2a',
    BURLYWOOD: '#deb887',
    CADETBLUE: '#5f9ea0',
    CHARTREUSE: '#7fff00',
    CHOCOLATE: '#d2691e',
    CORAL: '#ff7f50',
    CORNFLOWERBLUE: '#6495ed',
    CORNSILK: '#fff8dc',
    CRIMSON: '#dc143c',
    CYAN: '#00ffff',
    DARKBLUE: '#00008b',
    DARKCYAN: '#008b8b',
    DARKGOLDENROD: '#b8860b',
    DARKGRAY: '#a9a9a9',
    DARKGREEN: '#006400',
    DARKKHAKI: '#bdb76b',
    DARKMAGENTA: '#8b008b',
    DARKOLIVEGREEN: '#556b2f',
    DARKORANGE: '#ff8c00',
    DARKORCHID: '#9932cc',
    DARKRED: '#8b0000',
    DARKSALMON: '#e9967a',
    DARKSEAGREEN: '#8fbc8f',
    DARKSLATEBLUE: '#483d8b',
    DARKSLATEGRAY: '#2f4f4f',
    DARKTURQUOISE: '#00ced1',
    DARKVIOLET: '#9400d3',
    DEEPPINK: '#ff1493',
    DEEPSKYBLUE: '#00bfff',
    DIMGRAY: '#696969',
    DODGERBLUE: '#1e90ff',
    FIREBRICK: '#b22222',
    FLORALWHITE: '#fffaf0',
    FORESTGREEN: '#228b22',
    FUCHSIA: '#ff00ff',
    GAINSBORO: '#dcdcdc',
    GHOSTWHITE: '#f8f8ff',
    GOLD: '#ffd700',
    GOLDENROD: '#daa520',
    GRAY: '#808080',
    GREEN: '#008000',
    GREENYELLOW: '#adff2f',
    HONEYDEW: '#f0fff0',
    HOTPINK: '#ff69b4',
    INDIANRED: '#cd5c5c',
    INDIGO: '#4b0082',
    IVORY: '#fffff0',
    KHAKI: '#f0e68c',
    LAVENDER: '#e6e6fa',
    LAVENDERBLUSH: '#fff0f5',
    LAWNGREEN: '#7cfc00',
    LEMONCHIFFON: '#fffacd',
    LIGHTBLUE: '#add8e6',
    LIGHTCORAL: '#f08080',
    LIGHTCYAN: '#e0ffff',
    LIGHTGOLDENRODYELLOW: '#fafad2',
    LIGHTGREY: '#d3d3d3',
    LIGHTGREEN: '#90ee90',
    LIGHTPINK: '#ffb6c1',
    LIGHTSALMON: '#ffa07a',
    LIGHTSEAGREEN: '#20b2aa',
    LIGHTSKYBLUE: '#87cefa',
    LIGHTSLATEGRAY: '#778899',
    LIGHTSTEELBLUE: '#b0c4de',
    LIGHTYELLOW: '#ffffe0',
    LIME: '#00ff00',
    LIMEGREEN: '#32cd32',
    LINEN: '#faf0e6',
    MAGENTA: '#ff00ff',
    MAROON: '#800000',
    MEDIUMAQUAMARINE: '#66cdaa',
    MEDIUMBLUE: '#0000cd',
    MEDIUMORCHID: '#ba55d3',
    MEDIUMPURPLE: '#9370d8',
    MEDIUMSEAGREEN: '#3cb371',
    MEDIUMSLATEBLUE: '#7b68ee',
    MEDIUMSPRINGGREEN: '#00fa9a',
    MEDIUMTURQUOISE: '#48d1cc',
    MEDIUMVIOLETRED: '#c71585',
    MIDNIGHTBLUE: '#191970',
    MINTCREAM: '#f5fffa',
    MISTYROSE: '#ffe4e1',
    MOCCASIN: '#ffe4b5',
    NAVAJOWHITE: '#ffdead',
    NAVY: '#000080',
    OLDLACE: '#fdf5e6',
    OLIVE: '#808000',
    OLIVEDRAB: '#6b8e23',
    ORANGE: '#ffa500',
    ORANGERED: '#ff4500',
    ORCHID: '#da70d6',
    PALEGOLDENROD: '#eee8aa',
    PALEGREEN: '#98fb98',
    PALETURQUOISE: '#afeeee',
    PALEVIOLETRED: '#d87093',
    PAPAYAWHIP: '#ffefd5',
    PEACHPUFF: '#ffdab9',
    PERU: '#cd853f',
    PINK: '#ffc0cb',
    PLUM: '#dda0dd',
    POWDERBLUE: '#b0e0e6',
    PURPLE: '#800080',
    REBECCAPURPLE: '#663399',
    RED: '#ff0000',
    ROSYBROWN: '#bc8f8f',
    ROYALBLUE: '#4169e1',
    SADDLEBROWN: '#8b4513',
    SALMON: '#fa8072',
    SANDYBROWN: '#f4a460',
    SEAGREEN: '#2e8b57',
    SEASHELL: '#fff5ee',
    SIENNA: '#a0522d',
    SILVER: '#c0c0c0',
    SKYBLUE: '#87ceeb',
    SLATEBLUE: '#6a5acd',
    SLATEGRAY: '#708090',
    SNOW: '#fffafa',
    SPRINGGREEN: '#00ff7f',
    STEELBLUE: '#4682b4',
    TAN: '#d2b48c',
    TEAL: '#008080',
    THISTLE: '#d8bfd8',
    TOMATO: '#ff6347',
    TURQUOISE: '#40e0d0',
    VIOLET: '#ee82ee',
    WHEAT: '#f5deb3',
    WHITE: '#ffffff',
    WHITESMOKE: '#f5f5f5',
    YELLOW: '#ffff00',
    YELLOWGREEN: '#9acd32',
  } as Record<string, string>,
} as const;

export type Constants = typeof Constants;
